"""learning engine: topics and vocabulary

Revision ID: 38e26aa0c1ad
Revises: 49a41b29b2d9
Create Date: 2026-07-17 14:36:58.998257
"""
import uuid
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.domain.curriculum_reference import EVERYDAY_TOPICS, GRAMMAR_TOPICS

# revision identifiers, used by Alembic.
revision: str = '38e26aa0c1ad'
down_revision: str | None = '49a41b29b2d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

topic_table = sa.table(
    "grammar_topics",
    sa.column("id", sa.Uuid()),
    sa.column("language", sa.String()),
    sa.column(
        "category",
        sa.Enum("GRAMMAR", "EVERYDAY_TOPIC", name="topic_category", create_type=False),
    ),
    sa.column("name", sa.String()),
    sa.column("order_index", sa.Integer()),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_topics',
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('category', sa.Enum('GRAMMAR', 'EVERYDAY_TOPIC', name='topic_category'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_topic_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'MASTERED', name='topic_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['grammar_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic')
    )
    op.create_index(op.f('ix_user_topic_progress_topic_id'), 'user_topic_progress', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_topic_progress_user_id'), 'user_topic_progress', ['user_id'], unique=False)
    op.create_table('vocabulary_items',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('german', sa.String(length=255), nullable=False),
    sa.Column('english', sa.String(length=255), nullable=False),
    sa.Column('example_sentence', sa.String(length=500), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_items_user_id'), 'vocabulary_items', ['user_id'], unique=False)
    # ### end Alembic commands ###

    seed_rows = [
        {
            "id": uuid.uuid4(),
            "language": "de",
            "category": "GRAMMAR",
            "name": name,
            "order_index": index,
        }
        for index, name in enumerate(GRAMMAR_TOPICS)
    ] + [
        {
            "id": uuid.uuid4(),
            "language": "de",
            "category": "EVERYDAY_TOPIC",
            "name": name,
            "order_index": index,
        }
        for index, name in enumerate(EVERYDAY_TOPICS)
    ]
    op.bulk_insert(topic_table, seed_rows)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_items_user_id'), table_name='vocabulary_items')
    op.drop_table('vocabulary_items')
    op.drop_index(op.f('ix_user_topic_progress_user_id'), table_name='user_topic_progress')
    op.drop_index(op.f('ix_user_topic_progress_topic_id'), table_name='user_topic_progress')
    op.drop_table('user_topic_progress')
    op.drop_table('grammar_topics')
    # ### end Alembic commands ###
