"""AI tutor: memories, quizzes, conversations

Revision ID: 4bdbac7f97ac
Revises: 38e26aa0c1ad
Create Date: 2026-07-17 18:12:18.963412
"""
import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.domain.quiz_reference import QUIZ_QUESTIONS

# revision identifiers, used by Alembic.
revision: str = '4bdbac7f97ac'
down_revision: str | None = '38e26aa0c1ad'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

quiz_question_table = sa.table(
    "quiz_questions",
    sa.column("id", sa.Uuid()),
    sa.column("topic_id", sa.Uuid()),
    sa.column("question", sa.Text()),
    sa.column("options", sa.JSON().with_variant(postgresql.JSONB(), "postgresql")),
    sa.column("correct_option_index", sa.Integer()),
    sa.column("explanation", sa.Text()),
)

grammar_topic_table = sa.table(
    "grammar_topics",
    sa.column("id", sa.Uuid()),
    sa.column("name", sa.String()),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_memories',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('memory_type', sa.Enum('MISTAKE', 'FORGOTTEN_WORD', 'PRONUNCIATION_ISSUE', 'NOTE', name='memory_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('related_topic_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_topic_id'], ['grammar_topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_memories_user_id'), 'ai_memories', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['grammar_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_topic_id'), 'quiz_questions', ['topic_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('selected_option_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_question_id'), 'quiz_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###

    bind = op.get_bind()
    topic_rows = bind.execute(sa.select(grammar_topic_table.c.id, grammar_topic_table.c.name)).all()
    topic_id_by_name = {name: topic_id for topic_id, name in topic_rows}

    seed_rows = [
        {
            "id": uuid.uuid4(),
            "topic_id": topic_id_by_name[topic_name],
            "question": question,
            "options": options,
            "correct_option_index": correct_index,
            "explanation": explanation,
        }
        for topic_name, question, options, correct_index, explanation in QUIZ_QUESTIONS
    ]
    op.bulk_insert(quiz_question_table, seed_rows)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_question_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_quiz_questions_topic_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_ai_memories_user_id'), table_name='ai_memories')
    op.drop_table('ai_memories')
    # ### end Alembic commands ###
