"use client";

import * as React from "react";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PlanBlocks } from "@/components/planner/plan-blocks";
import { useTodayPlan } from "@/hooks/use-planner";

export default function PlannerPage() {
  const [availableMinutes, setAvailableMinutes] = React.useState(45);
  const { data, isLoading, isError } = useTodayPlan(availableMinutes);

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-semibold">Today&apos;s plan</h1>
        <p className="text-sm text-muted-foreground">
          Generated by the Planner Agent from your due vocabulary and unmastered topics.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>How much time do you have today?</CardTitle>
          <CardDescription>The plan below adjusts automatically.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col gap-1.5" style={{ maxWidth: 160 }}>
            <Label htmlFor="available_minutes">Minutes</Label>
            <Input
              id="available_minutes"
              type="number"
              min={5}
              max={300}
              value={availableMinutes}
              onChange={(e) => setAvailableMinutes(Number(e.target.value) || 45)}
            />
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Your plan</CardTitle>
          <CardDescription>
            {data
              ? `${data.vocab_due_count} words due · ${data.weak_topic_count} topics not yet mastered`
              : "Loading your current state…"}
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading && <p className="text-sm text-muted-foreground">Generating your plan…</p>}
          {isError && <p className="text-sm text-destructive">Couldn&apos;t generate a plan.</p>}
          {data && <PlanBlocks blocks={data.blocks} />}
        </CardContent>
      </Card>
    </div>
  );
}
